change_name_country <- function(df) {
    df <- df %>%
    mutate(
        Country = case_when(
        Country ==8 ~ "Albania",
        Country==31 ~ "Baku (Azerbaijan)",
        Country==32 ~ "Argentina",
        Country==36 ~ "Australia",
        Country==40 ~ "Austria",
        Country==56 ~"Belgium",
        Country==76 ~"Brazil",
        Country==96 ~"Brunei Darussalam",
        Country==100 ~"Bulgaria",
        Country==116 ~"Cambodia",
        Country==124 ~"Canada",
        Country==152 ~"Chile",
        Country==158 ~"Chinese Taipei",
        Country==170 ~"Colombia",
        Country==188 ~"Costa Rica",
        Country==191 ~"Croatia",
        Country==196 ~"Cyprus",
        Country==203 ~"Czech Republic",
        Country==208 ~"Denmark",
        Country==214 ~"Dominican Republic",
        Country==222 ~"El Salvador",
        Country==233 ~"Estonia",
        Country==246 ~"Finland",
        Country==250 ~"France",
        Country==268 ~"Georgia",
        Country==275 ~"Palestinian Authority",
        Country==276 ~"Germany",
        Country==300 ~"Greece",
        Country==320 ~"Guatemala",
        Country==344 ~"Hong Kong (China)",
        Country==348 ~"Hungary",
        Country==352 ~"Iceland",
        Country==360 ~"Indonesia",
        Country==372 ~"Ireland",
        Country==376 ~"Israel",
        Country==380 ~"Italy",
        Country==383 ~"Kosovo",
        Country==388 ~"Jamaica",
        Country==392 ~"Japan",
        Country==398 ~"Kazakhstan",
        Country==400 ~"Jordan",
        Country==410 ~"Korea",
        Country==428 ~"Latvia",
        Country==440 ~"Lithuania",
        Country==446 ~"Macao (China)",
        Country==458 ~"Malaysia",
        Country==470 ~"Malta",
        Country==484 ~"Mexico",
        Country==496 ~"Mongolia",
        Country==498 ~"Republic of Moldova",
        Country==499 ~"Montenegro",
        Country==504 ~"Morocco",
        Country==528 ~"Netherlands",
        Country==554 ~"New Zealand",
        Country==578 ~"Norway",
        Country==591 ~"Panama",
        Country==600 ~"Paraguay",
        Country==604 ~"Peru",
        Country==608 ~"Philippines",
        Country==616 ~"Poland",
        Country==620 ~"Portugal",
        Country==634 ~"Qatar",
        Country==642 ~"Romania",
        Country==682 ~"Saudi Arabia",
        Country==688 ~"Serbia",
        Country==702 ~"Singapore",
        Country==703 ~"Slovak Republic",
        Country==704 ~"Viet Nam",
        Country==705 ~"Slovenia",
        Country==724 ~"Spain",
        Country==752 ~"Sweden",
        Country==756 ~"Switzerland",
        Country==764 ~"Thailand",
        Country==784 ~"United Arab Emirates",
        Country==792 ~"Türkiye",
        Country==807 ~"North Macedonia",
        Country==826 ~"United Kingdom",
        Country==840 ~"United States",
        Country==858 ~"Uruguay",
        Country==860 ~"Uzbekistan",
        Country==901 ~"Ukrainian regions",
        
       TRUE ~ as.character(Country)  # Mantieni il numero del paese se non c'è corrispondenza
      )
    )
    return(df)   
}
